Updated PHP requirements
Bit-Wasp/bitcoin-php pull request #887
Opened 2021-10-17 20:09 UTC by n3omaster

When trying to required this package on a PHP 8 environment it returns an error.

2021-12-04 20:36 UTC, nomaxus approved these changes

2022-01-05 20:28 UTC, kapitonoval commented
"lastguest/murmurhash": "^2.0.0" - is not use php8

2022-02-19 18:36 UTC, bobbygrossmann commented
Hi i notice murmurhash 2.1.1 supportes php 8

2022-02-19 18:38 UTC, bobbygrossmann requested changes

2022-02-19 18:38 UTC, bobbygrossmann commented on composer.json
> +  "name": "n3omaster/bitcoin-php",
This is incorrect?

2022-10-05 06:52 UTC, BafS commented
If it can help we maintain a fork with PHP8.0+ compatibility: https://github.com/ProtonMail/bitcoin-php

2022-12-10 19:43 UTC, closed without merging